/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPortfolios"];
        put?: never;
        post: operations["createPortfolio"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["getPortfolio"];
        put: operations["updatePortfolio"];
        post?: never;
        delete: operations["deletePortfolio"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["getPortfolioSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["suggestContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/assets/{tickerSymbol}/ceiling": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                tickerSymbol: string;
            };
            cookie?: never;
        };
        get: operations["getCeiling"];
        put: operations["setCeiling"];
        post?: never;
        delete: operations["deleteCeiling"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/assets/{tickerSymbol}/ceiling/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCeilingHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/asset-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAssetSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ticker/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["registerTicker"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["getAllocations"];
        put?: never;
        post: operations["setAllocations"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/rebalance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["getRebalance"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ticker/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["searchTickers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ticker/{symbol}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTicker"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getQuote"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/movement": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["getMovements"];
        put?: never;
        post: operations["createMovement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/movement/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["importMovements"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/movement/{movementId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                movementId: number;
            };
            cookie?: never;
        };
        get: operations["getMovement"];
        put: operations["updateMovement"];
        post?: never;
        delete: operations["deleteMovement"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        get: operations["listShares"];
        put?: never;
        post: operations["createShare"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/portfolio/{portfolioId}/shares/{shareId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeShare"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/public/portfolio-shares/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getPublicShare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Exact decimal value; API may emit a JSON number until its wire contract is migrated. */
        Decimal: string | number;
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
        };
        RegisterRequest: {
            name: string;
            /** Format: email */
            email: string;
            password: string;
        };
        User: {
            /** Format: int64 */
            id?: number;
            name?: string;
            email?: string;
        };
        PortfolioRequest: {
            name: string;
        };
        Portfolio: {
            /** Format: int64 */
            id?: number;
            name?: string;
            totalAssets?: number;
        };
        PortfolioSummary: {
            /** Format: int64 */
            portfolioId?: number;
            totalInvested?: components["schemas"]["Decimal"];
            currentValue?: components["schemas"]["Decimal"];
            profitOrLoss?: components["schemas"]["Decimal"];
            percentageChange?: components["schemas"]["Decimal"];
            assetSummaries?: components["schemas"]["AssetSummary"][];
        };
        AssetSummary: {
            tickerSymbol?: string;
            quantity?: components["schemas"]["Decimal"];
            averagePrice?: components["schemas"]["Decimal"];
            totalInvested?: components["schemas"]["Decimal"];
            currentValue?: components["schemas"]["Decimal"];
            profitOrLoss?: components["schemas"]["Decimal"];
            percentageChange?: components["schemas"]["Decimal"];
        };
        SuggestionRequest: {
            amount: components["schemas"]["Decimal"];
            /** @default BRL */
            currency: string;
        };
        Suggestion: {
            requestedAmount?: components["schemas"]["Decimal"];
            allocatedAmount?: components["schemas"]["Decimal"];
            remainingAmount?: components["schemas"]["Decimal"];
            currency?: string;
            disclaimer?: string;
            items?: components["schemas"]["SuggestionItem"][];
            excludedAssets?: components["schemas"]["ExcludedAsset"][];
        };
        SuggestionItem: {
            tickerSymbol?: string;
            quantity?: components["schemas"]["Decimal"];
            unitPrice?: components["schemas"]["Decimal"];
            estimatedValue?: components["schemas"]["Decimal"];
            score?: components["schemas"]["Decimal"];
            ceilingPrice?: components["schemas"]["Decimal"];
            ceilingDistancePercentage?: components["schemas"]["Decimal"];
            dailyChangePercent?: components["schemas"]["Decimal"];
            currentPercentage?: components["schemas"]["Decimal"];
            targetPercentage?: components["schemas"]["Decimal"];
            reasons?: string[];
            quoteProvider?: string;
            /** Format: date-time */
            quoteObservedAt?: string;
        };
        ExcludedAsset: {
            tickerSymbol?: string;
            reason?: string;
        };
        CeilingRequest: {
            priceCeiling: components["schemas"]["Decimal"];
        };
        Ceiling: {
            tickerSymbol?: string;
            priceCeiling?: components["schemas"]["Decimal"];
        };
        CeilingHistory: {
            /** Format: int64 */
            id: number;
            tickerSymbol: string;
            previousPrice?: components["schemas"]["Decimal"] | null;
            priceCeiling?: components["schemas"]["Decimal"] | null;
            /** @enum {string} */
            action: "SET" | "REMOVED" | "BASELINE";
            /** Format: date-time */
            changedAt: string;
        };
        PageCeilingHistory: {
            content?: components["schemas"]["CeilingHistory"][];
            page?: components["schemas"]["PageMetadata"];
        };
        AssetSetting: {
            tickerSymbol: string;
            /** @enum {string} */
            category?: "EQUITIES" | "REAL_ESTATE_FUNDS" | "BDRS";
            categoryTargetPercentage: components["schemas"]["Decimal"];
            assetTargetPercentage: components["schemas"]["Decimal"];
            allocationPercentage: components["schemas"]["Decimal"];
            priceCeiling?: components["schemas"]["Decimal"] | null;
        };
        CategoryAllocation: {
            /** @enum {string} */
            category?: "EQUITIES" | "REAL_ESTATE_FUNDS" | "BDRS";
            categoryTargetPercentage?: components["schemas"]["Decimal"];
            assetAllocations?: {
                tickerSymbol?: string;
                targetPercentage?: components["schemas"]["Decimal"];
            }[];
        };
        Rebalance: {
            tickerSymbol?: string;
            /** @enum {string} */
            action?: "BUY" | "SELL";
            quantity?: components["schemas"]["Decimal"];
            currentPercentage?: components["schemas"]["Decimal"];
            targetPercentage?: components["schemas"]["Decimal"];
        };
        Ticker: {
            symbol?: string;
            tickerSymbol?: string;
            name?: string;
            category?: string;
            sector?: string;
            subSector?: string;
            priceCeiling?: components["schemas"]["Decimal"];
        };
        PageTickers: {
            content?: components["schemas"]["Ticker"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PageMovements: {
            content?: components["schemas"]["Movement"][];
            page?: components["schemas"]["PageMetadata"];
        };
        PageMetadata: {
            size?: number;
            number?: number;
            /** Format: int64 */
            totalElements?: number;
            totalPages?: number;
        };
        Quote: {
            symbol?: string;
            currency?: string;
            regularMarketTime?: string;
            /** Format: date-time */
            fetchedAt?: string;
            shortName?: string;
            longName?: string;
            regularMarketPrice?: components["schemas"]["Decimal"];
            regularMarketChange?: components["schemas"]["Decimal"];
            regularMarketChangePercent?: components["schemas"]["Decimal"];
            regularMarketDayHigh?: components["schemas"]["Decimal"];
            regularMarketDayLow?: components["schemas"]["Decimal"];
            regularMarketPreviousClose?: components["schemas"]["Decimal"];
            historicalDataPrice?: {
                /** Format: int64 */
                date?: number;
                close?: components["schemas"]["Decimal"];
            }[];
        };
        MovementRequest: {
            tickerSymbol: string;
            quantity: components["schemas"]["Decimal"];
            price: components["schemas"]["Decimal"];
            /** @enum {string} */
            type: "BUY" | "SELL";
            /** Format: date */
            date: string;
        };
        Movement: components["schemas"]["MovementRequest"] & {
            /** Format: int64 */
            id?: number;
        };
        CreateShareRequest: {
            /** Format: date-time */
            expiresAt: string;
            /** @default false */
            includeValues: boolean;
        };
        CreatedShare: {
            /** Format: int64 */
            id?: number;
            accessPath?: string;
            /** Format: date-time */
            expiresAt?: string;
            includeValues?: boolean;
        };
        Share: {
            /** Format: int64 */
            id?: number;
            /** Format: date-time */
            expiresAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            revokedAt?: string | null;
            includeValues?: boolean;
        };
        PublicShare: {
            /** Format: date-time */
            generatedAt?: string;
            /** Format: date-time */
            expiresAt?: string;
            includesValues?: boolean;
            assets?: {
                tickerSymbol?: string;
                quantity?: components["schemas"]["Decimal"];
                unitPrice?: components["schemas"]["Decimal"];
                marketValue?: components["schemas"]["Decimal"];
                currency?: string;
                quoteProvider?: string;
                /** Format: date-time */
                quoteObservedAt?: string;
            }[];
        };
        Error: {
            message?: string;
            details?: unknown;
        };
    };
    responses: {
        /** @description API error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        PortfolioId: number;
        Page: number;
        Size: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Access token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Registered user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listPortfolios: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"][];
                };
            };
        };
    };
    createPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioRequest"];
            };
        };
        responses: {
            /** @description Created portfolio */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getPortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    updatePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioRequest"];
            };
        };
        responses: {
            /** @description Updated portfolio */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Portfolio"];
                };
            };
        };
    };
    deletePortfolio: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPortfolioSummary: {
        parameters: {
            query?: {
                category?: string;
            };
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Portfolio valuation summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PortfolioSummary"];
                };
            };
        };
    };
    suggestContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionRequest"];
            };
        };
        responses: {
            /** @description Contribution simulation; does not create movements or orders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Suggestion"];
                };
            };
            400: components["responses"]["Error"];
            403: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    getCeiling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                tickerSymbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Asset ceiling preference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ceiling"];
                };
            };
        };
    };
    setCeiling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                tickerSymbol: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CeilingRequest"];
            };
        };
        responses: {
            /** @description Updated ceiling preference */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ceiling"];
                };
            };
        };
    };
    deleteCeiling: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                tickerSymbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCeilingHistory: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                tickerSymbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Price ceiling changes, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageCeilingHistory"];
                };
            };
        };
    };
    getAssetSettings: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured tickers, effective portfolio targets and ceilings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetSetting"][];
                };
            };
        };
    };
    registerTicker: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    symbol: string;
                    /** @enum {string} */
                    category: "EQUITIES" | "REAL_ESTATE_FUNDS" | "BDRS";
                };
            };
        };
        responses: {
            /** @description Registered or existing ticker; never changes existing category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticker"];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getAllocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Target allocations by category and ticker */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryAllocation"][];
                };
            };
        };
    };
    setAllocations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CategoryAllocation"][];
            };
        };
        responses: {
            /** @description Allocations saved */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["Error"];
        };
    };
    getRebalance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rebalance recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rebalance"][];
                };
            };
        };
    };
    searchTickers: {
        parameters: {
            query?: {
                symbol?: string;
                sector?: string;
                subSector?: string;
                category?: "EQUITIES" | "REAL_ESTATE_FUNDS" | "BDRS";
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageTickers"];
                };
            };
        };
    };
    getTicker: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                symbol: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ticker detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ticker"];
                };
            };
        };
    };
    getQuote: {
        parameters: {
            query: {
                ticker: string;
                range?: string;
                interval?: string;
                fundamental?: boolean;
                dividends?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market quote and optional price history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Quote"];
                };
            };
            503: components["responses"]["Error"];
        };
    };
    getMovements: {
        parameters: {
            query?: {
                page?: components["parameters"]["Page"];
                size?: components["parameters"]["Size"];
            };
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paged movements */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageMovements"];
                };
            };
        };
    };
    createMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description Movement created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"];
                };
            };
        };
    };
    importMovements: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Imported movements */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"][];
                };
            };
            400: components["responses"]["Error"];
        };
    };
    getMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                movementId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Movement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"];
                };
            };
        };
    };
    updateMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                movementId: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MovementRequest"];
            };
        };
        responses: {
            /** @description Updated movement */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Movement"];
                };
            };
        };
    };
    deleteMovement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                movementId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Share links without their secret tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Share"][];
                };
            };
        };
    };
    createShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShareRequest"];
            };
        };
        responses: {
            /** @description Created link path; treat as secret */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedShare"];
                };
            };
        };
    };
    revokeShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolioId: components["parameters"]["PortfolioId"];
                shareId: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicShare: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Read-only snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicShare"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
}
