spring.application.name=investment-app
brapi.api.token=kudT4RSj9HrGGgGMJ8h3WF
security.jwt.secret-key=4597fa4d3caebdb301065080fbdf892bf0301f9a846aade18d1d710bb8ce97897f618fcb564840b4ae81e7d5c641b8eef94fb3a6ebd9a275a62da2c02cba661050e6fd58b184b38f4ffa05a43d1431fae3aacb766681372282b914a9826905959759bd39780de0a4a09e49ceba774962f12f38b20b1305bd567fae5a402e900c761c2f43504d0e0e4a7b860bd5ff82e365c3d0cc5f19e37d7f1a17dc908a465bb8cd51e462de87bc0bf0e23f54b75896f64c6cc115280e45dc0ebee0f867a831f2faa572fa78e2825de5fbea9c942714f9d41a01305b250775ccae7d3bd4a8360a36c6816d07f50b394392c946ec0a626f292284825ddc80477b0bb54ea6c3dd
security.jwt.expiration-time=1000000

#
## PostgreSQL Database Connection
#spring.datasource.url=jdbc:postgresql://localhost:5432/investmentdb
#spring.datasource.username=investmentuser
#spring.datasource.password=investmentpass
#spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# Cache Configuration
spring.cache.type=caffeine
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=30m

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Server Port
server.port=8080
