CREATE SEQUENCE role_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE role (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE _user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE users_roles (
    user_id BIGINT NOT NULL REFERENCES _user(id),
    role_id BIGINT NOT NULL REFERENCES role(id),
    PRIMARY KEY (user_id, role_id)
);

CREATE TABLE portfolio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    user_id BIGINT NOT NULL REFERENCES _user(id)
);

CREATE TABLE ticker (
    symbol VARCHAR(255) PRIMARY KEY,
    category VARCHAR(255),
    sector VARCHAR(255),
    sub_sector VARCHAR(255),
    price_ceiling NUMERIC(19, 4)
);

CREATE TABLE asset_movement (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT REFERENCES portfolio(id),
    ticker_symbol VARCHAR(255),
    quantity NUMERIC(38, 8),
    price NUMERIC(19, 4),
    date DATE,
    type VARCHAR(255)
);

CREATE TABLE category_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolio(id),
    category VARCHAR(255) NOT NULL,
    target_percentage NUMERIC(5, 2) NOT NULL,
    CONSTRAINT uk_category_allocation_portfolio_category UNIQUE (portfolio_id, category)
);

CREATE TABLE asset_allocation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker_symbol VARCHAR(255) NOT NULL REFERENCES ticker(symbol),
    target_percentage NUMERIC(5, 2) NOT NULL,
    category_allocation_id BIGINT NOT NULL REFERENCES category_allocation(id)
);

INSERT INTO role (id, name) VALUES
    (nextval('role_seq'), 'ROLE_USER'),
    (nextval('role_seq'), 'ROLE_ADMIN');
