CREATE TABLE portfolio_asset_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolio(id) ON DELETE CASCADE,
    ticker_symbol VARCHAR(255) NOT NULL REFERENCES ticker(symbol),
    price_ceiling NUMERIC(19, 4) NOT NULL,
    CONSTRAINT uk_portfolio_asset_preference UNIQUE (portfolio_id, ticker_symbol),
    CONSTRAINT ck_portfolio_asset_preference_price_ceiling CHECK (price_ceiling > 0)
);

CREATE INDEX idx_asset_movement_portfolio_ticker ON asset_movement (portfolio_id, ticker_symbol);
