CREATE TABLE price_ceiling_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolio(id) ON DELETE CASCADE,
    ticker_symbol VARCHAR(255) NOT NULL REFERENCES ticker(symbol),
    previous_price NUMERIC(19, 4),
    price_ceiling NUMERIC(19, 4),
    action VARCHAR(16) NOT NULL,
    changed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_ceiling_history_previous CHECK (previous_price IS NULL OR previous_price > 0),
    CONSTRAINT ck_ceiling_history_price CHECK (price_ceiling IS NULL OR price_ceiling > 0),
    CONSTRAINT ck_ceiling_history_action CHECK (action IN ('SET', 'REMOVED', 'BASELINE'))
);

CREATE INDEX idx_ceiling_history_portfolio_ticker
    ON price_ceiling_history (portfolio_id, ticker_symbol, changed_at, id);

-- Existing values are a baseline at migration time, not a reconstructed edit date.
INSERT INTO price_ceiling_history (portfolio_id, ticker_symbol, price_ceiling, action, changed_at)
SELECT portfolio_id, ticker_symbol, price_ceiling, 'BASELINE', CURRENT_TIMESTAMP
FROM portfolio_asset_preference;
