-- B3 Position Import tables
-- Stores the complete history of B3 position snapshots imported per portfolio.
-- Each import is compared against the previous to identify position changes.

CREATE TABLE b3_position_import (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id       BIGINT        NOT NULL REFERENCES portfolio(id),
    user_id            BIGINT        NOT NULL REFERENCES _user(id),
    file_name          VARCHAR(500)  NOT NULL,
    file_hash          VARCHAR(64)   NOT NULL,
    total_assets_found INTEGER       NOT NULL DEFAULT 0,
    imported_at        TIMESTAMP     NOT NULL,
    status             VARCHAR(20)   NOT NULL,
    error_message      TEXT,
    previous_import_id BIGINT        REFERENCES b3_position_import(id),
    CONSTRAINT uk_b3_import_portfolio_hash UNIQUE (portfolio_id, file_hash)
);

CREATE INDEX idx_b3_import_portfolio_id ON b3_position_import (portfolio_id);
CREATE INDEX idx_b3_import_portfolio_status ON b3_position_import (portfolio_id, status, imported_at DESC);

-- Stores each individual asset position item from a B3 snapshot
CREATE TABLE b3_position_item (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_import_id     BIGINT         NOT NULL REFERENCES b3_position_import(id),
    ticker_symbol          VARCHAR(20)    NOT NULL,
    product_name           VARCHAR(500),
    asset_type             VARCHAR(30)    NOT NULL,
    asset_subtype          VARCHAR(50),
    quantity               NUMERIC(38, 8) NOT NULL,
    quantity_available     NUMERIC(38, 8),
    quantity_unavailable   NUMERIC(38, 8),
    unavailability_reason  VARCHAR(255),
    closing_price          NUMERIC(19, 4),
    updated_value          NUMERIC(19, 4),
    institution            VARCHAR(500),
    account                VARCHAR(100),
    isin_code              VARCHAR(100),
    cnpj                   VARCHAR(20)
);

CREATE INDEX idx_b3_position_item_import_id ON b3_position_item (position_import_id);
CREATE INDEX idx_b3_position_item_ticker ON b3_position_item (ticker_symbol);

-- Stores detected changes between consecutive B3 position snapshots
CREATE TABLE b3_position_change (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_import_id BIGINT         NOT NULL REFERENCES b3_position_import(id),
    ticker_symbol      VARCHAR(20)    NOT NULL,
    change_type        VARCHAR(30)    NOT NULL,
    previous_quantity  NUMERIC(38, 8),
    current_quantity   NUMERIC(38, 8),
    quantity_delta     NUMERIC(38, 8) NOT NULL
);

CREATE INDEX idx_b3_position_change_import_id ON b3_position_change (position_import_id);
