DROP TABLE IF EXISTS b3_position_change;
DROP TABLE IF EXISTS b3_position_item;
DROP TABLE IF EXISTS b3_position_import;

CREATE TABLE b3_import_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL REFERENCES portfolio(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES _user(id) ON DELETE CASCADE,
    file_name VARCHAR(255) NOT NULL,
    file_hash VARCHAR(255) NOT NULL,
    total_negotiations_found INT NOT NULL DEFAULT 0,
    new_negotiations INT NOT NULL DEFAULT 0,
    already_imported INT NOT NULL DEFAULT 0,
    inconsistencies INT NOT NULL DEFAULT 0,
    imported_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(50) NOT NULL,
    error_message TEXT
);

ALTER TABLE asset_movement ADD COLUMN external_reference VARCHAR(255) UNIQUE;
